# Generated by Django 5.2.10 on 2026-01-31 14:06

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "impossible_travel",
            "0022_remove_tasksettings_unique_task_execution_mode_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="login",
            index=models.Index(fields=["-timestamp"], name="login_timestamp_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="login",
            index=models.Index(fields=["ip"], name="login_ip_idx"),
        ),
        migrations.AddIndex(
            model_name="login",
            index=models.Index(fields=["event_id"], name="login_event_id_idx"),
        ),
        migrations.AddIndex(
            model_name="login",
            index=models.Index(
                django.db.models.functions.text.Upper("country"),
                name="login_country_upper_idx",
            ),
        ),
    ]
