# Generated by Django 5.2.10 on 2026-01-31 14:23

import ipaddress
from django.db import migrations, models


def delete_invalid_login_ips(apps, schema_editor):
    Login = apps.get_model("impossible_travel", "Login")
    for login in Login.objects.all().only("id", "ip"):
        try:
            ipaddress.ip_address(login.ip)
        except ValueError:
            login.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("impossible_travel", "0023_login_login_timestamp_desc_idx_login_login_ip_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_invalid_login_ips),
        migrations.AlterField(
            model_name="login",
            name="ip",
            field=models.GenericIPAddressField(protocol="both", unpack_ipv4=True),
        ),
    ]
